collections:
  authors:
    output: True
  papers:
    output: True
  projects:
    output: True
  students:
    output: True

defaults:
  -
    scope:
      path: ""
    values:
      search_exclude: true
  -
    scope:
      path: "search"
    values:
      layout: "search"
